### PR TITLE
Fixes bug with opening lot info 📱

### LINKED ISSUE #1866: [Live UI] Tapping lot info makes info disappear completely
enter live auction, tap lot info, lot info button disappears and no lot info is shown 
image

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #1866. Also adds some documenting comments.

The bug's cause was two interfering autolayout constraints, so I got rid of `topMetadataStackConstraint` and used only `alignMetadataToTopConstraint`. This PR is a work-in-progress because the view controller I modified is almost 400 lines of code, with a quarter of that devoted _just_ to a gesture recognizer. I want to move that into its own object.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm. 

screen shot 2016-09-28 at 4 37 00 pm

Any idea why this is failing for me?

File: Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift [hunk 1]
```diff
@@ -315,6 +327,8 @@ class LiveAuctionLotViewController: UIViewController {
 
         default: break
         }
+
+        print(alignMetadataToTopConstraint?.constant)
```
Comment (robertherdzik) [inline Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift]: I'm curious what is the purpose of leaving log?

Comment (ashfurrow) [inline Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift]: Ah, no purpose, just an accident :wink:

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG changes made</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |264.6ms | [AuctionViewController.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
193.7ms | [SwiftyJSON.swift](/artsy/eigen/tree/lot-info-hide-fix/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
170.2ms | [WebSocket.swift](/artsy/eigen/tree/lot-info-hide-fix/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
94.9ms | [SwiftyJSON.swift](/artsy/eigen/tree/lot-info-hide-fix/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L794) | get {}
87.9ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
85.6ms | [Observable.swift](/artsy/eigen/tree/lot-info-hide-fix/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
80.1ms | [AuctionOrdering.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Auction/AuctionOrdering.swift#L17) | func sortSaleArtworks<T : AuctionOrderable>(saleArtworks: [T]) -> [T]
75.4ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
72.8ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
68.0ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
66.0ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
60.6ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/lot-info-hide-fix/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ashfurrow** [comment]
Seeing this error from dependency-ci:

screen shot 2016-09-30 at 3 17 35 pm

Tried re-authorizing the app, no joy. I think it's my account. Can we review without it?

**Comment by orta** [comment]
we've been seeing depCI issues all week, probably more scaling issues

**Comment by ashfurrow** [comment]
Ah, gotcha. Thought it was just me 😅

File: Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift [hunk 2]
```diff
@@ -198,6 +243,7 @@ class LiveAuctionLotViewController: UIViewController {
         // This should occur during the view's initial layout pass, before any user interaction.
         if atRestMetadataPosition == nil {
             atRestMetadataPosition = lotMetadataStack?.frame.origin.y
+            print("Resetting atRestMetadataPosition to \(atRestMetadataPosition)")
```
Comment (orta) [inline Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift]: assumably superfluous

Comment (ashfurrow) [inline Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift]: I flip flopped on that, but I'll take it out.

Comment (orta) [inline Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift]: Cool, I'm fine either way - good to go then

Comment (ashfurrow) [inline Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift]: Cool!
