### PR TITLE
Analytics fixes for v3

### LINKED ISSUE #1939: [Analytics] Eigen 3.0 QA
## Screens
We should attempt to move towards firing a single screenview per screen. Onboarding screenviews that are double firing currently:
- [x] `Onboarding start` and `sign_up_splash`: we should deprecate `sign_up_splash` and only fire `Onboarding start`

 

- [x] `Onboarding signup` and `create_account`: we should deprecate `create_account` and only fire `Onboarding signup`

 

- [x] `Onboarding login` and `login`: we should deprecate `login` and only fire `Onboarding login`

 

- [x] Every other onboarding screen fires a proper screenview and an additional screenview `personalize` which should be removed; we should only fire `Onboarding follow artists`, `Onboarding follow categories`, `Onboarding select budget`

- [ ] Pressing the home button and the app while on an onboarding screen and then opening it again does not fire another screenview, and maybe it should if we consider reopening the app the start of a new session; a similar thing is happening with events, in the below case `Follow artist`:

screen recording 2016-10-18 at 14 33

## Tracks
- [x] When following a category from the Onboarding follow categories screen, a `gene favorite` track -- an outdated event with no properties -- fires. Instead, we should fire `Follow category`. Nore that a category can be followed from a gene page or during onboarding. Contextual properties:
  * properties: {  
                         gene_id,  
                         source_screen: [gene page, onboarding top categories, onboarding search, onboarding recommended]  
                         }

- [x] `Follow artist` fires with no contextual properties. Instead we should append to the event:
  * properties: {  
                         artist_slug,  
                         artist_id,  
                         source_screen:[artist page, artist fair page, onboarding top artists, onboarding search, onboarding recommended]  
                         }

- [x] We do not fire an event when user logs in using safari keychain. Instead, we should fire `Successfully logged in` with the following property:
  * properties: {  
                        context_type: safari keychain  
                        }  

img_0167 2

### PR DESCRIPTION
**Pull request by ashfurrow**
Here're the analytics fixes for v3. Some notes:

- Duplicate events with old names were caused by some code left in from the old onboarding that would produce a sort of "catch all". So if we showed the user a view with a class named "ARPersonalizeViewController", we would mangle that into "personalize". @anipetrov Please double check that removing this behaviour didn't accidentally remove any page views we were relying on.
- Firing another page view event when the app goes from foreground -> background -> foreground again is difficult. I've left it out for now, because it really affects how the whole app should work, and the feature would ideally be built into the ARAnalytics library itself. Happy to chat about this, maybe it's something we can squeeze in for v3, but it definitely needs a conversation.

Fixes #1939.

### CODE REVIEW

File: Artsy/App/ARAppDelegate+Analytics.m [hunk 1]
```diff
@@ -877,8 +885,8 @@ - (void)setupAnalytics
                         @{
                             ARAnalyticsEventName: ARAnalyticsGeneFollow,
                             ARAnalyticsSelectorName: NSStringFromSelector(@selector(categoryFollowed:)),
-                            ARAnalyticsProperties: ^NSDictionary*(ARPersonalizeViewController *controller, NSArray *_){
-//                                Gene *gene = _.firstObject;
+                            ARAnalyticsProperties: ^NSDictionary*(ARPersonalizeViewController *controller, NSArray *params){
+                                Gene *gene = params.firstObject;
                                 NSString *sourceScreen = @"";
                                 if (controller.searchResultsTable.contentDisplayMode == ARTableViewContentDisplayModePlaceholder) {
                                     sourceScreen = @"onboarding top artists";
```
Comment (mennenia) [inline Artsy/App/ARAppDelegate+Analytics.m]: This is probably my fault as I've copied it and left it 'top artists' but any chance you could change it to 'onboarding top categories'?

File: Artsy/App/ARAppDelegate+Analytics.m [hunk 2]
```diff
@@ -1006,9 +1014,16 @@ - (void)setupAnalytics
                                 return sender.isHearted == YES;
                             },
                             ARAnalyticsProperties: ^NSDictionary*(ARArtistViewController *controller, NSArray *parameters){
+                                NSString *sourcePage = @"";
+                                if (controller.fair) {
+                                    sourcePage = @"artist fair page";
+                                } else {
+                                    sourcePage = @"artist page";
```
Comment (mennenia) [inline Artsy/App/ARAppDelegate+Analytics.m]: We may need an additional event here for Artist Follows from the new Home view... Left a comment on the original issue, and will double check!

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |232.5ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
182.6ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
160.7ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
83.3ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
75.0ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
68.3ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
66.8ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
60.8ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
59.1ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-analytics-v3-showstoppers/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>
