### PR TITLE
Fix for onboarding tableview crasher

### LINKED ISSUE #1988: Fix NSRangeException in - [AROnboardingPersonalizeTableViewController updateTableContentsFor:replaceContents:animated:], line 68
### Stacktrace ###

<pre>AROnboardingPersonalizeTableViewController;updateTableContentsFor:replaceContents:animated:;AROnboardingPersonalizeTableViewController.m;68
ARPersonalizeViewController;categoryFollowed:;ARPersonalizeViewController.m;316</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/143258922](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/143258922)

### PR DESCRIPTION
**Pull request by sarahscott**
Tricky one; fixes #1988

### CODE REVIEW

**Comment by alloy** [comment]
Can you add CHANGELOG entry? And also for that previous gene VC change?

**Comment by sarahscott** [comment]
The only problem here is if network cuts out, the user can't get past the gene selection stage. At least now the app won't crash, but it's worth thinking about network failure handling here so we have a good contingency plan.

**Comment by sarahscott** [comment]
I can't actually repro this even if I cut network a bunch of times at different stages. When testing, I just set `searchResults` to an empty array and was able to get it to crash that way.

**Comment by alloy** [comment]
@sarahscott otoh, if there’s no network the Home view would also not load, although I agree that some sort of warning message might be in order.

File: Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m [hunk 1]
```diff
@@ -61,14 +61,13 @@ - (void)updateTableContentsFor:(NSArray *)searchResults
...
-
     switch (replaceStyle) {
         case ARSearchResultsReplaceSingle:
-            if (searchResults) {
+            if (searchResults.count) {
                 [self.searchResults replaceObjectAtIndex:self.tableView.indexPathForSelectedRow.row withObject:searchResults[0]];
                 self.selectedRowToReplace = self.tableView.indexPathForSelectedRow;
                 [self.geneImageReconciler addReplacedGene:self.selectedRowToReplace];
-            } else {
+            } else if (self.searchResults.count) {
```
Comment (alloy) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m]: Why is this guard needed?

Comment (sarahscott) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m]: Because it will also crash if `removeObjectAtIndex` is called on `self.searchResults` if it's empty.

Comment (sarahscott) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/AROnboardingPersonalizeTableViewController.m]: Can be repro'd by setting `searchResults` to an empty array when the network connection is down.

File: CHANGELOG.yml [hunk 2]
```diff
@@ -1,14 +1,22 @@
...
-    details: Patch fix for 3.0.0 release.
+    version: 3.0.2
+    details: Second patch fix for 3.0.0 release.
     dev:
       infrastructure:
     user_facing:
-      - Fixes an intermittent crash on the live interface - ash
-      - Attempts to fix a crash that would occur by sending a message to a search VC that it doesn’t implement - alloy
+      - Fixes gene routing bug where search routed to old gene VC instead of RN one - sarah
+      - Fixes tableview crasher in onboarding - sarah + maxim
```
Comment (alloy) [inline CHANGELOG.yml]: This fix was only made by you, right?

Comment (sarahscott) [inline CHANGELOG.yml]: Maxim's fix for 3.0.1 was almost the entire soltuion and I just made it more robust. Her fix wasn't in the changelog though

Comment (alloy) [inline CHANGELOG.yml]: Got it 👍

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Release 3.0.1 does not have a date</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">You need to set the App’s plist version to 3.0.2</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |255.1ms | [AuctionViewController.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
196.4ms | [SwiftyJSON.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
176.5ms | [WebSocket.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
99.7ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
81.2ms | [Observable.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
74.5ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
72.5ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
66.1ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
64.1ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/sarah-onboarding-crasher-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mennenia** [comment]
Great stuff @sarahscott! ❤️

**Comment by sarahscott** [comment]
this one is 🍏 @alloy

**Comment by alloy** [comment]
Ace!
