### PR TITLE
@1aurabrown => [Feed] Force refresh content when network becomes available.

### LINKED ISSUE #624: app permanently stuck without ability to get back online
I have been refreshing the app trying to get passed the network error screen for over half the day with no luck. had to delete and restart the app. Previous issues I logged may all be related. Trouble is, I don't know how to reproduce. I think it all started from trying to access the app when there was no network connection and never getting connected again.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #624.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
There are going to be changelog conflicts

**Comment by alloy** [comment]
@1aurabrown Rebased!

File: Artsy/View_Controllers/Feed_VCs/ARShowFeedViewController.m [hunk 1]
```diff
@@ -51,7 +51,7 @@ - (instancetype)initWithFeedTimeline:(ARFeedTimeline *)timeline
 
     _heroUnitVC = [[ARHeroUnitViewController alloc] init];
 
-   @_weakify(self);
```
Comment (1aurabrown) [inline Artsy/View_Controllers/Feed_VCs/ARShowFeedViewController.m]: is `@_weakify` different from `@weakify`?

Comment (alloy) [inline Artsy/View_Controllers/Feed_VCs/ARShowFeedViewController.m]: Yeah, @orta replaced them all with `@_weakify` because of how libextobjc is exposed and how that doesn’t work the same with the new frameworks setup.

**Comment by alloy** [comment]
@1aurabrown Rebased, again!
