### PR TITLE
@orta => Auction related fixes.

### LINKED ISSUE #890: tapping bid from auction sale overview page does not redirect to native artwork view
I didn't account for this case when testing before but if a user bids from the sale overview page
(force view) 
image

https://staging.artsy.net/auction/los-angeles-modern-auctions-march-2015

that means they get lead to a (force) confirmation screen directly 
image

and as a result get this instead of the result of the bid on a native artwork view 
image

if I start a bid from a native artwork view on the ipad, then I get the nice updated native artwork view when i finish confirming my bid on the force view. 

Is there a way to land a user coming from the sale overview page on a native artwork view?

### PR DESCRIPTION
**Pull request by alloy**
Fixes #890 and #893.

### CODE REVIEW

File: Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m [hunk 1]
```diff
@@ -113,7 +113,7 @@ - (void)tappedContactRepresentative
 
 - (void)tappedAuctionInfo
 {
-    ARInternalMobileWebViewController *viewController = [[ARInternalMobileWebViewController alloc] initWithURL:[NSURL URLWithString:@"/auction-info"]];
+    ARInternalMobileWebViewController *viewController = [[ARInternalMobileWebViewController alloc] initWithURL:[NSURL URLWithString:@"/how-auctions-work"]];
```
Comment (orta) [inline Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m]: I think @katarinabatina said specifically for iPad, does this work fine on iPhone?

Comment (alloy) [inline Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m]: No it was both iPad and iPhone: #893
