### PR TITLE
@orta => Fix xcode 6.4 warnings

### LINKED ISSUE #695: Get rid of all warnings

### PR DESCRIPTION
**Pull request by alloy**
Closes #695.

There’s a whole bunch of iOS 9 warnings with Xcode 7, but some of those can’t be fixed without breaking it on Xcode 6 or having to resort to ugly additional macros, so I’m not bothering with that for now until Xcode 7 is GM.

Can you please review this commit specifically, as it’s related to changes you made updating CocoaLumberjack and AFNetworking https://github.com/artsy/eigen/commit/4c209c5884b2fad1fde24c430c51f3b11c404a2b

### CODE REVIEW

File: Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h [hunk 1]
```diff
@@ -59,7 +59,7 @@
 
 /// Returns the index of the tab that holds the given view controller at the root of the navigation stack or
 /// `NSNotFound` in case it’s not a root view controller.
-- (ARTopTabControllerIndex)indexOfRootViewController:(UIViewController *)viewController;
+- (NSInteger)indexOfRootViewController:(UIViewController *)viewController;
```
Comment (orta) [inline Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h]: what was happening here?

Comment (alloy) [inline Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h]: The actual implementation didn’t match, it stated to return a `NSInteger`. I could have changed that implementation, but because the method returns `NSNotFound` when no VC is matched, I figured it made more sense to use `NSInteger` instead.

**Comment by orta** [comment]
glad to see the Gemfile.lock updates :+1:
