### PR TITLE
[Emission] Hook-up gene status API module.

### LINKED ISSUE #1924: Fix crash in - [ARTemporaryAPIModule followStatusForGene:completion:], line 19
### Stacktrace ###

<pre>ARTemporaryAPIModule;followStatusForGene:completion:;ARTemporaryAPIModule.m;19
RCTModuleMethod;invokeWithBridge:module:arguments:;RCTModuleMethod.m;484
RCTBatchedBridge;callNativeModule:method:params:;RCTBatchedBridge.m;1035
RCTBatchedBridge;handleBuffer:;RCTBatchedBridge.m;976</pre>

### Reason ###

Selector name found in current argument registers: geneFollowStatusProvider

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/140606378](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/140606378)

### PR DESCRIPTION
**Pull request by alloy**
Fixes #1924

### CODE REVIEW

File: Artsy/App/ARAppDelegate+Emission.m [hunk 1]
```diff
@@ -122,18 +99,58 @@ - (void)setupSharedEmissionWithPackagerURL:(NSURL *)packagerURL;
                                         useStagingEnvironment:[AROptions boolForOption:ARUseStagingDefault]];
     [AREmission setSharedInstance:emission];
 
+#pragma mark - Native Module: Follow status
+
     emission.APIModule.artistFollowStatusProvider = ^(NSString *artistID, RCTResponseSenderBlock block) {
-        // Leave the view state ‘unselected’ if there’s no signed-in user.
-        if ([[ARUserManager sharedManager] currentUser] != nil) {
-            ArtistGetFollowStatus(artistID, block);
-        }
```
Comment (alloy) [inline Artsy/App/ARAppDelegate+Emission.m]: There is always a signed-in user now! 🎉
