### PR TITLE
[WorksForYou] Fix layout on ipad after rotation.

### LINKED ISSUE #1312: WFU ipad layout not working when rotated, layout structure doesn't seem right in general
Looking at the iPad it seems like every new batch of works adheres to a different set of rules. Sometimes two works are centered, sometimes left aligned. When rotating the iPad the works don't fill in newly available columns. 

If  we were to use our standard masonry view for each of these artwork groupings it would mean that a single work wouldn't take up so much of the viewport as it would be fixed to a 2-column width. The scale shift between an artist that has one artwork versus another that has two is so large I easily scroll by some of the batches of work. 

image

### PR DESCRIPTION
**Pull request by alloy**
Fixes #1312

### CODE REVIEW

File: Artsy/View_Controllers/WorksForYou/ARWorksForYouNotificationItemViewController.m [hunk 1]
```diff
@@ -195,13 +197,13 @@ - (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIVi
 }
 
 #pragma mark - ARArtworkMasonryLayoutProvider
+
 - (ARArtworkMasonryLayout)masonryLayoutForSize:(CGSize)size
 {
-    if (self.artworksVC.items.count > 1) {
```
Comment (alloy) [inline Artsy/View_Controllers/WorksForYou/ARWorksForYouNotificationItemViewController.m]: Removed this, because there’s never going to be embedded models when there’s just 1 artwork.

File: Artsy/View_Controllers/WorksForYou/ARWorksForYouNotificationItemViewController.m [hunk 2]
```diff
@@ -195,13 +197,13 @@ - (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIVi
...
-        return self.traitCollection.horizontalSizeClass == UIUserInterfaceSizeClassRegular && self.artworksVC.items.count >= 3 ? ARArtworkMasonryLayout3Column : ARArtworkMasonryLayout2Column;
-
```
Comment (alloy) [inline Artsy/View_Controllers/WorksForYou/ARWorksForYouNotificationItemViewController.m]: Wrapped this around the 120 columns line.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Warning</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by sarahscott** [comment]
:tada:
