### PR TITLE
[Facebook] Fix crash when account does not have associated email

### LINKED ISSUE #2095: Crash on login
Get started ->
Follow Artists that Interest you most -> Next->
Follow Categories of Art that Interest you most -> Next->
Do you have a budget in Mind -> Under $500 -> Next
Set up your artsy account -> Connect with Facebook

Of particular note: the facebook account I am using only uses a phone number, no email.

### PR DESCRIPTION
**Pull request by mennenia**
Fix #2095. 

Currently, the fix is that we do not accept Facebook accounts that don't have primary emails - we give the user a warning with what the issue is. 

This seemed simpler for now than having a separate screen that allows users to enter an email (like we used to), because in that case, I would say that users can create an email account instead. 

@orta  - sorry, more indentation grief!

### CODE REVIEW

File: Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m [hunk 1]
```diff
@@ -391,39 +391,49 @@ - (void)fb:(id)sender
...
+                                                                          // this facebook account is already an artsy account
+                                                                          // let's log them in
+                                                                          [sself loginWithFacebookCredentialToken:token];
+                                                                          return;
+                                                                      } else if ([JSON[@"error"] isEqualToString:@"User Already Exists"]
+                                                                                 || [JSON[@"error"] isEqualToString:@"User Already Invited"]) {
+                                                                          // there's already a user with this email
+                                                                          NSString *source = [self existingAccountSource:JSON];
+                                                                          [sself accountExists:source];
+                                                                          return;
```
Comment (orta) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: this is 💯

File: Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m [hunk 2]
```diff
@@ -391,39 +391,49 @@ - (void)fb:(id)sender
...
-                                                              NSString *errorMessage = [NSString stringWithFormat:@"Server replied saying '%@'.", JSON[@"error"] ?: JSON[@"message"] ?: error.localizedDescription];
-                                                              
-                                                              // we'll display an alert view
-                                                              [sself showErrorAlertWithMessage:errorMessage];
-        }];
+                                                                  
+                                                                  // something else went wrong
+                                                                  ARErrorLog(@"Couldn't link Facebook account. Error: %@. The server said: %@", error.localizedDescription, JSON);
+                                                                  
+                                                                  NSString *errorMessage = [NSString stringWithFormat:@"Server replied saying '%@'.", JSON[@"error"] ?: JSON[@"message"] ?: error.localizedDescription];
```
Comment (orta) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: perhaps "Facebook responded with:"  instead of "Server said" ?

File: Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m [hunk 3]
```diff
@@ -391,39 +391,49 @@ - (void)fb:(id)sender
...
+                                                                  [sself showErrorAlertWithMessage:errorMessage];
+            }];
+
+    } else {
+        // provide popup warning asking the user to use a Facebook account with email
+        [self ar_removeIndeterminateLoadingIndicatorAnimated:YES];
+
+        UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Couldn’t create your account" message:@"Please use a Facebook account that has an email address" delegate:nil cancelButtonTitle:@"Dismiss" otherButtonTitles:nil];
+        alert.tag = ERROR_TAG;
+        [alert show];
```
Comment (orta) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: a bit cruel, but better than a crash

Comment (mennenia) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: well, that's what I was thinking.. 

Whichever way you put it, `ARUserManager` needs an email (a phone number wouldn't do), and asking for an email again, whilst the email field is kinda _right there_, seems odd too.

File: Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m (hunk 2 above)
Comment (mennenia) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: Sure thing - that's been there forever, happy to change

Comment (mennenia) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: at this point, it's no longer facebook - it's our own server / API..

File: Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m (hunk 3 above)
Comment (mennenia) [inline Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m]: I could add more text, e.g. suggesting they sign up for an email account. I ended up taking that out to simplify.

**Comment by ShirleyPerkins** [comment]
If you start using automated validation tools early on, you can increase tremendously the efficiency of your testing. Your end user wouldn't need to find the bugs themselves. I learned this from this article:  [](http://blog.testproject.io/2017/01/04/why-use-automated-validation-tools-early/)

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
Lols this spam was removed super quickly

screen shot 2017-01-12 at 10 53 01 am

Went to report it, and it was already gone

**Comment by orta** [comment]
Alright 👍
