### PR TITLE
Fixes auction name running off edge

### LINKED ISSUE #1361: Auction Sale name text not wrapping to
the sale title should be wrapping not going off the screen 
image

### PR DESCRIPTION
**Pull request by ashfurrow**
`preferredMaxLayoutWidth` strikes again :disappointed: 

Fixes #1361.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">2 Warnings</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td>Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
This also restores our lovely test output: 

screen shot 2016-03-24 at 8 49 58 pm

File: Artsy/Views/Auction/AuctionTitleView.swift [hunk 1]
```diff
@@ -88,7 +88,8 @@ private extension AuctionTitleView {
     }
 
     func titleView() -> UIView {
-        let container = UIView()
+        // container needs a reasonable-ish size when we add the titleLabel, so its preferredMaxLayoutWidth gets set to something non-zero.
+        let container = UIView(frame: CGRect(origin: CGPoint.zero, size: UIScreen.mainScreen().bounds.size))
```
Comment (alloy) [inline Artsy/Views/Auction/AuctionTitleView.swift]: :disappointed:

https://github.com/artsy/Artsy-UILabels/pull/20

File: Artsy/Views/Auction/AuctionTitleView.swift [hunk 2]
```diff
@@ -98,8 +99,13 @@ private extension AuctionTitleView {
         container.addSubview(titleLabel)
 
         if fullWidth {
-            titleLabel.alignLeadingEdgeWithView(container, predicate: "0")
             titleLabel.alignTop("0", bottom: "0", toView: container)
+            titleLabel.alignLeadingEdgeWithView(container, predicate: "0")
+
+            // If we're showing the info button, we'll anchor trailing space to that later, but if not, we need to anchor to the container.
+            if showAdditionalInformation == false {
```
Comment (alloy) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Is it Swifty to compare against literal booleans?

File: Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift [hunk 3]
```diff
@@ -268,6 +281,27 @@ class AuctionViewControllerTests: QuickSpec {
...
         }
 
+        it("handles showing information for upcoming auctions with long names with no sale artworks") {
+            let exact_now = ISO8601DateFormatter().dateFromString("2025-11-24T10:00:00+00:00")!
+            let start = exact_now.dateByAddingTimeInterval(3600.9)
+            let end = exact_now.dateByAddingTimeInterval(3700.9)
+            freezeTime(exact_now)
+
+            sale = try! Sale(dictionary: [
+                "saleID": "the-tada-sale", "name": "The Sale With The Really Really Looooong Name",
```
Comment (alloy) [inline Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift]: Perfect this, I love how you made it so that it exactly showcases the correct wrapping :+1:

File: Artsy/Views/Auction/AuctionTitleView.swift (hunk 1 above)
Comment (ashfurrow) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Ah, sorry :disappointed:

File: Artsy/Views/Auction/AuctionTitleView.swift (hunk 2 above)
Comment (ashfurrow) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Depends who you ask, I think so.

File: Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift (hunk 3 above)
Comment (ashfurrow) [inline Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift]: :bow:

File: Artsy/Views/Auction/AuctionTitleView.swift (hunk 1 above)
Comment (alloy) [inline Artsy/Views/Auction/AuctionTitleView.swift]: No no! The link was just about leaving a papertrail.

Comment (ashfurrow) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Ah, just read the convo there, makes sense :smile:

File: Artsy/Views/Auction/AuctionTitleView.swift (hunk 2 above)
Comment (ashfurrow) [inline Artsy/Views/Auction/AuctionTitleView.swift]: I do this in Objective-C too. `!someBooleanVariable` is waaaay too easy to misread imo.

Comment (alloy) [inline Artsy/Views/Auction/AuctionTitleView.swift]: It’s a fair point, basically we have to depend on text editors with syntax highlighting to ‘fix’ that problem.

I much prefer something like Ruby’s `unless` over all these.

Comment (ashfurrow) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Wanna pair on a proposal to Swift Evolution?

Comment (alloy) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Hell, why not!

Comment (alloy) [inline Artsy/Views/Auction/AuctionTitleView.swift]: FYI, one thing people might say is that you can define a function for it, for instance like seen here https://gist.github.com/JadenGeller/2828e1f7458c8b41a7b0. But as can also be seen in that example, a negated function then also begs for a non-negated one (`when`) because of consistent readability, which I think nobody really wants.

Comment (AliSoftware) [inline Artsy/Views/Auction/AuctionTitleView.swift]: Or maybe you could:
```swift
prefix operator ❗️ {}
func ❗️(rhs: BooleanConvertible) -> Bool { return !Bool(rhs)
}
```

Not sure ❗️ is a valid operator but if it is, no way to miss that inversion :wink:
